### ISSUE TITLE
[DOCS] Support Envoy access log

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [kitabisa/teler#101]
## Summary

I want to integrate the Envoy access log with Teler, a lot of service mesh tooling use Envoy as the main proxy. Do you know any variable that teler support from the access log itself? So I can make a PR with the correct Envoy format.

Some recommended topics to cover:
N/A

### Motivation
- Envoy used in service mesh like Istio

**Comment by dwisiswant0** [comment]
Hi, @zufardhiyaulhaq. Have you seen discussion #86? It's great there to start, we're also preparing documentation to support any custom logs format.
If you have a related question, feel free to open a new discussion.
