### ISSUE TITLE
[DOCS] Apache Log Example Incorrect

### ISSUE THREAD

**Issue by ossie-git** [kitabisa/teler#115]
**Describe the bug**

The Apache log format example in the official documentation looks like this:

```
log_format: |
  $remote_addr - $remote_user [$time_local] "$request_method $request_uri $request_protocol" $status $body_bytes_sent
```

but it will not match because it misses the last two fields. Instead, it should look like this:

```
log_format: |
  $remote_addr - $remote_user [$time_local] "$request_method $request_uri $request_protocol" $status $body_bytes_sent "$http_referer" "$http_user_agent"
```

**Comment by dwisiswant0** [comment]
Good spot, @ossie-git. I'm not sure because I didn't test all of them one by one. Closing as per 86ab500.

**Comment by dwisiswant0** [comment]
@all-contributors please add @ossie-git for doc.
