### ISSUE TITLE
Where are the config files located?

### ISSUE THREAD

**Issue by CaledoniaProject** [kitabisa/teler#122]
Where can I find those files?

```
common-web-attacks.json
cves.json
bad-ip-addresses.txt
bad-referrers.txt
bad-crawlers.txt
directory-bruteforces.txt
```

**Comment by dwisiswant0** [comment]
Hi, @CaledoniaProject. Basically, its under user-level cache directory on each platform.

Windows: `%LOCALAPPDATA%\teler-resources` or `C:\Users\%USER%\AppData\Local\teler-resources`
Linux: `%XDG_CACHE_HOME/teler-resources` or `$HOME/.cache/teler-resources`
OSX: `$HOME/Library/Caches/teler-resources`

**Comment by CaledoniaProject** [comment]
It's not in the github repo?

**Comment by CaledoniaProject** [comment]
The binary release does not even contain any config files, it's useless if you don't provide those files mentioned above.

**Comment by dwisiswant0** [comment]
Of course it's stored on [GitHub repository](https://github.com/kitabisa/teler-resources), and when teler is executed it will be downloaded & stored to the user-cache directory of its user. Please refer to [Resources](https://github.com/kitabisa/teler#resources) section.
