### ISSUE TITLE
[ASK] Teler won't build

### ISSUE THREAD

**Issue by pieterhouwen** [kitabisa/teler#173]
**Describe the bug**

Cannot run make build. Exits with following errors:

![image](https://user-images.githubusercontent.com/10866686/128541875-aaca02ad-7386-4d35-8a44-7c374dad1b2f.png)

**To Reproduce**

On a fresh Ubuntu install, install golang, clone the repo and run make build.

```yaml
Your teler config file...
The default one.

// Please redacted your token and/ other sensitive informations
```

**Expected behavior**

It builds without errors

**Screenshots**

**Environment (please complete the following information):**

- OS: Ubuntu Bionic (18.04)
- OS version: Linux vpn-machine 4.15.0-151-generic #157-Ubuntu SMP Fri Jul 9 23:07:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- teler Version N/A

**Additional context**
Add any other context about the problem here. Full output log is probably a helpful thing to add here.

- See screenshot

**Comment by dwisiswant0** [comment]
What version of Go are you using, @pieterhouwen?
