### ISSUE TITLE
[DOCS] Docker volume and port missing

### ISSUE THREAD

**Issue by loretoparisi** [kitabisa/teler#261]
## Summary
The [documentation](https://teler.app/usage) about `Docker` is missing parameters for volume `-v` and port `-p` in order to export the console to `8080` and to share the local files (`yaml` config file and logging) to the container:

```
docker run -i --rm -p 8080:8080 -v `pwd`:/teler -e TELER_CONFIG=/teler/teler.yaml kitabisa/teler --input `pwd`/logs/20221007.txt
```

### Motivation

Correctly load local host files into the container; binding the dashboard port to the host.

**Comment by dwisiswant0** [comment]
Thanks for spotting this, @loretoparisi.

**Comment by loretoparisi** [comment]
@dwisiswant0 you are welcome, just realized that even if I can see

```
ip-192-168-20-210:teler loretoparisi$ ./teler.sh 

          __      __       
         / /____ / /__ ____
        / __/ -_) / -_) __/
        \__/\__/_/\__/_/   
                        v2.0.0-rc.3

        infosec@kitabisa.com

[WRN] This tool is under development!
[WRN] Please submit a report if an error occurs.
[INF] Analyzing...
[INF] Listening dashboard on http://127.0.0.1:8080
```

I cannot access the server in the browser at `localhost`. Typically this is due to the loopback address interface `127.0.0.1`. You should start the server with `0.0.0.0` in order to make it working externally at the port binded with `-p 8080:8080`.

NOTE
Content of `teler.sh` was 

```
docker run -i --rm -p 8080:8080 -v `pwd`:/teler -e TELER_CONFIG=/teler/teler.yaml kitabisa/teler -x 30 --input `pwd`/logs/20221007.txt
```

**Comment by loretoparisi** [comment]
**[UPDATE]**
I did it!!!
<img width="1651" alt="Schermata 2022-10-14 alle 14 53 03" src="https://user-images.githubusercontent.com/163333/195851715-a18022b0-2d03-4fdd-bde0-d991be052b7e.png">

Just added the `dashboard` option to `teler.yaml` using `0.0.0.0` as correct `host` for `localhost`!

```yaml
dashboard:
  active: true
  host: "0.0.0.0"
  port: 8080
  username: "xxx"
  password: "xxx"
  endpoint: "/events"
```

The problem is that the `Waiting for Events` is spinning indefinitely even if I have passed a log from file with

```
--input `pwd`/logs/20221007.txt
```

Not sure if this is due to a bad log format. My log format is a `pure-ftpd` and looks like

```
# Oct  6 07:08:12 c49701 pure-ftpd: (user@site.com@XX.XX.XX.XX) [NOTICE] /home/some_path some_file.txt downloaded  (539258 bytes, 5426.32KB/sec)
log_format: |
  $date $time $x $x $x@site.com@$remote_addr $x $request_uri $request_method $x $x
```

where I have used `$request_uri` for the file path and `$request_method` for the file name (maybe i't wrong).
