### ISSUE TITLE
[FEATURE] Telegram notification alerts

### ISSUE THREAD

**Issue by dwisiswant0** [kitabisa/teler#36]

**Comment by zufardhiyaulhaq** [comment]
Hey, I am interesting helping for telegram notification. It is possible?

**Comment by dwisiswant0** [comment]
> Hey, I am interesting helping for telegram notification. It is possible?

Yes, with pleasure @zufardhiyaulhaq. For more information, see the [CONTRIBUTING.md](https://github.com/kitabisa/teler/blob/master/.github/CONTRIBUTING.md) guidelines.

**Comment by zufardhiyaulhaq** [comment]
@dwisiswant0 do you have a log example that you can provide since mostly I am working with the envoy and not really experience simulating attacking behavior.

**Comment by dwisiswant0** [comment]
> @dwisiswant0 do you have a log example that you can provide since mostly I am working with the envoy and not really experience simulating attacking behavior.

Here's a sample log from Nginx: https://ghostbin.co/paste/ha2497, and use this log format, see: https://github.com/kitabisa/teler#nginx.

Let me know if you need more information, @zufardhiyaulhaq.

**Comment by zufardhiyaulhaq** [comment]
thanks, I figure out generating log with `dirb` + apache2 also. Will send PR for telegram. Thanks

**Comment by zufardhiyaulhaq** [comment]
@dwisiswant0 did you know what is the permission for the slack bot? I need to see the example log in slack. This error probably permission error
```
teler $ cat example.log | ./bin/teler  -c /root/github/teler/teler.yaml                                                      master*

          __      __       
         / /____ / /__ ____
        / __/ -_) / -_) __/
        \__/\__/_/\__/_/   
                        v0.0.1-beta3.2

        infosec@kitabisa.com

[WRN] This tool is under development!
[WRN] Please submit a report if an error occurs.
[ERR] Error! Only validates Slack channel; please check your config file
[INF] Use "-h" flag for more info about command.
```

**Comment by dwisiswant0** [comment]
You've to fill the channel value with channel ID, not with channel name, @zufardhiyaulhaq.
