### ISSUE TITLE
[BUG] cannot detect the attack

### ISSUE THREAD

**Issue by DeskiAriSandi** [kitabisa/teler#377]
**Describe the bug**
Here I don't understand how to use the latest version

**To Reproduce**

I just changed the log format to apache2 format log. without configuring anything else. but when running it, Teler cannot detect the attack

**Expected behavior**

What I hope is that I know how to use the latest version of Teler. I don't understand the change from excludes to whitelists

**Screenshots**
<img width="643" alt="Screenshot 2024-01-23 104010" src="https://github.com/kitabisa/teler/assets/108607379/eec5b3a3-4204-4875-b705-e97067e9539d">

**Environment (please complete the following information):**

- OS: [linux]
- OS version: [apache2]
- teler Version [v2.0.0-dev.3-4-g1319fc0]

**Additional context**
Add any other context about the problem here. Full output log is probably a helpful thing to add here.

**Comment by dwisiswant0** [comment]
Please see https://github.com/kitabisa/teler/discussions/86 to define `log_format` properly.
