### ISSUE TITLE
[FEATURE] Add Exporters to Prometheus

### ISSUE THREAD

**Issue by JustHumanz** [kitabisa/teler#41]
**Is your feature request related to a problem? Please describe.**
add exporters in teler, so we can get a statistical data 

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by JustHumanz** [comment]
nice, let me help it

**Comment by dwisiswant0** [comment]
> nice, let me help it

Please give more contexts.

**Comment by JustHumanz** [comment]
> > nice, let me help it
> 
> Please give more contexts.

well i experience with Prometheus and i think this tools will be great if can integrate with Prometheus
so i can monitoring resource and security at one time
