### ISSUE TITLE
[FEATURE] Add Traefik log parsing

### ISSUE THREAD

**Issue by SakiiR** [kitabisa/teler#65]
All in the title.

Currently, this handles text logs like a charm, but it could get a bit complicated to parse JSON output like traefik does.

**Comment by dwisiswant0** [comment]
Not sure if you have followed the `log_format` structure, because there shouldn't be a problem.
If you don't minde, can I see an example of that Traefik _(just 1 log line)_, and how do you define `log_format` on the teler configuration file, @SakiiR?

**Comment by SakiiR** [comment]
By default, traefik logs the output in JSON.

The JSON entries are "dynamic" and gives different output depending on what kind of request has been received.

https://doc.traefik.io/traefik/observability/access-logs/#format

The CLF format is handled fine, but not the JSON one. 

This is just a feature request.

**Comment by dwisiswant0** [comment]
Yes, even though it's dynamic, I have to see how dummy log samples is, so that I can reproduce, enhance and/or fix the problem you are facing easily, @SakiiR.

**Comment by SakiiR** [comment]
Yes I tried to find examples online, but could not find it.

Let me some time, and I will provide you an example.

**Comment by JustHumanz** [comment]
[here](https://gist.github.com/JustHumanz/e7da56c45d0fac75fb93e6005e9b18f4),i'm made some examples with gobuster and sqlmap

i use "Web For Pentester" for the target

**Comment by dwisiswant0** [comment]
Hi @SakiiR, please check the [answer](https://github.com/kitabisa/teler/discussions/86#discussioncomment-194019) for #86 discussion about how to define custom log format for teler configuration.

I hope that clears up your problem!
