### ISSUE TITLE
[BUG] make build

### ISSUE THREAD

**Issue by brownchow** [kitabisa/teler#94]
**command line option  -v, the output is always 1.0.1**

run `bin/teler -v`  the output is always
```sh
$ bin/teler -v
teler 1.0.1
```
cause the version varibale defined in [constants.go](https://github.com/kitabisa/teler/blob/62623bcb3d6071f8c96d816980a36906b402e659/internal/runner/constants.go#L5) **is not overwritten** at build time in [Makefile](https://github.com/kitabisa/teler/blob/62623bcb3d/Makefile#L30)

**To Reproduce**
just clone the repo, and run `make build` to compile the binary, then run `bin/teler -v`
the output is always 
```sh
$ bin/teler -v
teler 1.0.1
```

**Expected behavior**
at this time, the output version should be
```sh
 bin/teler -v
teler v1.0.1-29-g62623bc
```
if we tag a new commit, the `-v` option should produce a new version

**Screenshots**
sorry for my company network environment, I can just describe in text

**Environment:**
I think this bug should reproduce in all OS
I am using windows10 and git-bash
- OS: [windows10]
- OS version: [windows10]
- teler Version the problem is about version, so ........

**Comment by bedo-501** [comment]
‫أُرسلت من الـ iPhone‬

**Comment by bedo-501** [comment]
﻿


‫أُرسلت من الـ iPhone‬

**Comment by bedo-501** [comment]
﻿

‫أُرسلت من الـ iPhone‬

بداية الرسالة المحولة:

> من: Badr Alharthy <badar_501@icloud.com>
> التاريخ: ٢٩ ديسمبر، ٢٠٢٠، ٧:٢٩:٤١ ص غرينتش+٣
> إلى: Badr Alharthy <badar_501@icloud.com>
> الموضوع: I’m just going to be a little bit more on the
> 
> ﻿https://media.discordapp.net/attachments/712980483293708329/793330561653538836/image0.png
> 
> 
> ‫أُرسلت من الـ iPhone‬
